name: REPARTO BANDA APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Instalar dependencias
        run: npm install

      - name: Crear proyecto Android
        run: npx cap add android

      - name: Sincronizar aplicación
        run: npx cap sync android

      - name: Compilar APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: REPARTO-BANDA-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
